# -*- coding: utf-8 -*-
"""Bank Database.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Re-TUTu1GWypeM8aDFdAsxeG6C3ySoq
"""

!pip install dnspython
!-m pip install pymongo[srv]

import pandas as pd

import pymongo
#pymongo version
from pymongo import MongoClient
#client = pymongo.MongoClient("mongodb+srv://surbhigarg757:surbhi321@cluster0.mbw4s.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")

client = pymongo.MongoClient("mongodb+srv://surbhigarg757:surbhi321@cluster0.mbw4s.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")
#bank_database is database name
db = client.bank_database
#inside bank_database we have bank_details
records=db.bank_details

correct_input= lambda input:print("\nPlease enter correct input\n")

def option():
  print("\nEnter respective numbers to:\n")
  print("Create new account: 1\nDeposit Amount: 2\nWithdraw Amount: 3\nCheck Balance: 4\nExit :5")
  a=input()
  if(a=="1"):
    create_account()
  elif(a=="2"):
    deposit_amount()
  elif(a=="3"):
    withdraw_amount()
  elif(a=="4"):
    check_balance()
  elif(a=="5"):
    print("Thank you!")
    exit()
  else:
    correct_input(1)
    option()

def more_operations():
  print("\nExit: 1\nPerform more functions: 2\n")
  a=input()
  if(a=="1"):
    print("Thank you!")
    exit()
  elif(a=="2"):
    option()
  else:
    correct_input(1)
    more_operations()

def create_account():
  name=input("Enter name: ").capitalize()
  while(name.isalpha()!=1):
    print("Please note name only contains alphabet")
    correct_input(1)
    name=input("Enter name: ").capitalize()
  aadhar=input("Enter Aadhaar number: ")
  while(len(aadhar)!=12 or aadhar.isdigit()==0):
    print("Please note adhaar card should contain 12 digits")
    correct_input(1)
    aadhar=input("Enter Aadhaar number: ")
  pan=input("Enter PAN number: ")
  while(len(pan)!=10 or pan[:5].isalpha()==0 or pan[5:9].isdigit()==0 or pan[9].isalpha()==0):
    correct_input(1)
    pan=input("Enter PAN number: ")
  email=input("Enter emailid: ")
  while("@" not in email or "." not in email):
    correct_input(1)
    email=input("Enter emailid: ")
  type_acc=input("Press respective number for\nCurrent: 1\nSaving: 2\n")
  while(type_acc!="1" and type_acc!="2"):
    correct_input(1)
    type_acc=input("Press respective number for\nCurrent: 1\nSaving: 2")
  if(type_acc=="1"):
    type_acc="Current"
  else:
    type_acc="Saving"
  Account_number=aadhar[:4]+pan[5:8]
  details={"Name":name,"Aadhar":aadhar,"PAN":pan,"Email":email,"Type":type_acc,"Account_number":Account_number,"Amount(Rs)":int(0)}
  records.insert_one(details)
  print("Account created sucessfully! Your account number is ",Account_number)
  for x in records.find(details,{"_id":0,"Name":1,"Aadhar":1,"PAN":1,"Email":1,"Type":1,"Account_number":1,"Amount(Rs)":1}):
    print(pd.DataFrame(x,index=["Details"]))
  more_operations()

def deposit_amount():
  y=input("Please enter your account number or name: ")
  if(y.isdigit()):
    myquery={"Account_number":y}
  else:
    myquery={"Name":y.capitalize()}
  if records.count_documents(myquery)== 0:
    print("Invalid Details!")
    deposit_amount()
  else:
    amount=input("Please enter amount to be deposited: Rs")
    while(amount.isdigit()==0):
      print("Invalid value!")
      amount=input("Please enter amount to be deposited: Rs")
    newvalues={"$inc":{"Amount(Rs)":int(amount)}}
  #to update one/many
    records.update_one(myquery,newvalues)
    print("Congratulations! Amount is deposited sucessfully!")
    for x in records.find(myquery,{"_id":0,"Name":1,"Account_number":1,"Amount(Rs)":1}):
      print(pd.DataFrame(x,index=["Details"]))
      break
    more_operations()

def withdraw_amount():
  y=input("Please enter your account number or name: ")
  if(y.isdigit()):
    myquery={"Account_number":y}
  else:
    myquery={"Name":y.capitalize()}
  while records.count_documents(myquery)== 0:
    print("Invalid Details!")
    y=input("Please enter your account number or name: ")
    if(y.isdigit()):
      myquery={"Account_number":y}
    else:
      myquery={"Name":y.capitalize()}
  amount=input("Please enter withdrawal amount: Rs")
  while(amount.isdigit()==0):
    print("Invalid value!")
    amount=input("Please enter withdrawal amount: Rs")
  for x in records.find(myquery,{"_id":0,"Amount(Rs)":1}):
    y=x["Amount(Rs)"]
    break
  if(y<int(amount)):
    print("You have insufficient balance! Your balance is ",y)
  else:
    newvalues={"$inc":{"Amount(Rs)":-int(amount)}}
    records.update_one(myquery,newvalues)
    print("Congratulations! Amount is withdrawan sucessfully!")
    for x in records.find(myquery,{"_id":0,"Amount(Rs)":1}):
      print("Balance in your account: ",x["Amount(Rs)"])
      break
  more_operations()

def check_balance():
  y=input("Please enter your account number or name: ")
  if(y.isdigit()):
    myquery={"Account_number":y}
  else:
    myquery={"Name":y.capitalize()}
  if records.count_documents(myquery)== 0:
    print("Invalid Details!")
    check_balance()
  for x in records.find(myquery,{"_id":0,"Amount(Rs)":1}):
    print("Balance in your account: ",x["Amount(Rs)"])
    break
  more_operations()

records.drop()

print("Welcome to Bank!\n")
option()